"use client"

import { useEffect, useState } from 'react';
import Link from 'next/link';
import { motion } from 'framer-motion';
import { Button } from '@/components/ui/button';
import { Card, CardContent } from '@/components/ui/card';
import { Badge } from '@/components/ui/badge';
import Navbar from '@/components/Navbar';
import Footer from '@/components/Footer';
import { 
  Dumbbell, 
  Brain, 
  Trophy, 
  Sparkles, 
  Calendar, 
  TrendingUp,
  Zap,
  Star,
  ArrowRight,
  CheckCircle2
} from 'lucide-react';

export default function Home() {
  const [quote, setQuote] = useState('Your fitness journey starts here');
  const [isLoading, setIsLoading] = useState(true);

  useEffect(() => {
    // Fetch motivational quote from Gemini API
    const fetchQuote = async () => {
      try {
        const response = await fetch('/api/motivational-quote');
        if (response.ok) {
          const data = await response.json();
          setQuote(data.quote);
        }
      } catch (error) {
        console.error('Failed to fetch quote');
      } finally {
        setIsLoading(false);
      }
    };

    fetchQuote();
  }, []);

  const features = [
    {
      icon: Brain,
      title: 'AI-Powered Plans',
      description: 'Get personalized workout and diet plans generated by advanced AI technology',
      gradient: 'from-purple-500 to-pink-500'
    },
    {
      icon: Dumbbell,
      title: 'Custom Workouts',
      description: 'Tailored exercise routines based on your fitness level, goals, and preferences',
      gradient: 'from-blue-500 to-cyan-500'
    },
    {
      icon: Calendar,
      title: 'Meal Planning',
      description: 'Personalized nutrition plans that match your dietary needs and preferences',
      gradient: 'from-green-500 to-emerald-500'
    },
    {
      icon: Trophy,
      title: 'Gamification',
      description: 'Earn XP, level up, maintain streaks, and compete on the leaderboard',
      gradient: 'from-yellow-500 to-orange-500'
    },
    {
      icon: Zap,
      title: 'Quiz Games',
      description: 'Test your fitness knowledge and earn rewards with AI-generated quizzes',
      gradient: 'from-red-500 to-pink-500'
    },
    {
      icon: TrendingUp,
      title: 'Progress Tracking',
      description: 'Monitor your achievements, stats, and export detailed PDF reports',
      gradient: 'from-indigo-500 to-purple-500'
    }
  ];

  const testimonials = [
    {
      name: 'Marcus Rodriguez',
      username: 'FitWarrior',
      avatar: 'https://api.dicebear.com/7.x/avataaars/svg?seed=FitWarrior',
      content: 'The AI-generated workout plans are incredibly accurate and effective. Lost 15 pounds in 2 months!',
      rating: 5,
      level: 51
    },
    {
      name: 'Sarah Chen',
      username: 'IronPulse',
      avatar: 'https://api.dicebear.com/7.x/avataaars/svg?seed=IronPulse',
      content: 'Love the gamification system! The streak feature keeps me motivated every single day.',
      rating: 5,
      level: 43
    },
    {
      name: 'David Kim',
      username: 'ZenAthlete',
      avatar: 'https://api.dicebear.com/7.x/avataaars/svg?seed=ZenAthlete',
      content: 'The meal plans are perfect for my busy lifestyle. Easy to follow and actually enjoyable!',
      rating: 5,
      level: 36
    }
  ];

  return (
    <div className="min-h-screen bg-gradient-to-b from-background to-muted/20">
      <Navbar />
      
      {/* Hero Section */}
      <section className="container px-4 py-20 md:py-32">
        <div className="grid lg:grid-cols-2 gap-12 items-center">
          <motion.div
            initial={{ opacity: 0, x: -50 }}
            animate={{ opacity: 1, x: 0 }}
            transition={{ duration: 0.5 }}
            className="space-y-8"
          >
            <Badge className="w-fit" variant="secondary">
              <Sparkles className="w-3 h-3 mr-1" />
              AI-Powered Fitness Coach 2.0
            </Badge>
            
            <h1 className="text-4xl md:text-6xl font-bold leading-tight">
              Transform Your Body with{' '}
              <span className="bg-gradient-to-r from-purple-600 via-pink-600 to-blue-600 bg-clip-text text-transparent">
                AI Precision
              </span>
            </h1>
            
            <p className="text-lg md:text-xl text-muted-foreground">
              Get personalized workout plans, custom diet recommendations, and gamified progress tracking 
              powered by advanced AI technology. Your ultimate fitness companion is here.
            </p>

            <motion.div
              initial={{ opacity: 0 }}
              animate={{ opacity: 1 }}
              transition={{ delay: 0.3 }}
              className="p-4 bg-gradient-to-r from-purple-500/10 via-pink-500/10 to-blue-500/10 rounded-lg border border-purple-500/20"
            >
              <p className="text-sm font-medium text-muted-foreground mb-1">💪 Motivational Quote</p>
              <p className="text-lg font-semibold italic">
                {isLoading ? 'Loading inspiration...' : `"${quote}"`}
              </p>
            </motion.div>

            <div className="flex flex-col sm:flex-row gap-4">
              <Link href="/signup">
                <Button size="lg" className="w-full sm:w-auto group">
                  Get Started Free
                  <ArrowRight className="w-4 h-4 ml-2 group-hover:translate-x-1 transition-transform" />
                </Button>
              </Link>
              <Link href="/login">
                <Button size="lg" variant="outline" className="w-full sm:w-auto">
                  Sign In
                </Button>
              </Link>
            </div>

            <div className="flex items-center gap-8 pt-4">
              <div>
                <p className="text-2xl font-bold">10K+</p>
                <p className="text-sm text-muted-foreground">Active Users</p>
              </div>
              <div>
                <p className="text-2xl font-bold">50K+</p>
                <p className="text-sm text-muted-foreground">Plans Generated</p>
              </div>
              <div>
                <p className="text-2xl font-bold">4.9★</p>
                <p className="text-sm text-muted-foreground">User Rating</p>
              </div>
            </div>
          </motion.div>

          <motion.div
            initial={{ opacity: 0, x: 50 }}
            animate={{ opacity: 1, x: 0 }}
            transition={{ duration: 0.5 }}
            className="relative"
          >
            <div className="relative w-full aspect-square max-w-lg mx-auto">
              <img
                src="https://images.unsplash.com/photo-1571019614242-c5c5dee9f50b?w=800&h=800&fit=crop"
                alt="Fitness"
                className="rounded-2xl shadow-2xl object-cover w-full h-full"
              />
              <div className="absolute inset-0 bg-gradient-to-tr from-purple-600/20 to-blue-600/20 rounded-2xl" />
            </div>
          </motion.div>
        </div>
      </section>

      {/* Features Section */}
      <section className="container px-4 py-20 bg-muted/50">
        <div className="text-center mb-12">
          <Badge className="mb-4" variant="secondary">Features</Badge>
          <h2 className="text-3xl md:text-5xl font-bold mb-4">
            Everything You Need to Succeed
          </h2>
          <p className="text-lg text-muted-foreground max-w-2xl mx-auto">
            Powerful AI-driven features designed to help you achieve your fitness goals faster
          </p>
        </div>

        <div className="grid md:grid-cols-2 lg:grid-cols-3 gap-6">
          {features.map((feature, index) => (
            <motion.div
              key={index}
              initial={{ opacity: 0, y: 20 }}
              whileInView={{ opacity: 1, y: 0 }}
              transition={{ duration: 0.5, delay: index * 0.1 }}
              viewport={{ once: true }}
            >
              <Card className="h-full hover:shadow-lg transition-shadow">
                <CardContent className="p-6 space-y-4">
                  <div className={`w-12 h-12 rounded-lg bg-gradient-to-br ${feature.gradient} flex items-center justify-center`}>
                    <feature.icon className="w-6 h-6 text-white" />
                  </div>
                  <h3 className="text-xl font-semibold">{feature.title}</h3>
                  <p className="text-muted-foreground">{feature.description}</p>
                </CardContent>
              </Card>
            </motion.div>
          ))}
        </div>
      </section>

      {/* Testimonials Section */}
      <section className="container px-4 py-20">
        <div className="text-center mb-12">
          <Badge className="mb-4" variant="secondary">Testimonials</Badge>
          <h2 className="text-3xl md:text-5xl font-bold mb-4">
            Loved by Fitness Enthusiasts
          </h2>
          <p className="text-lg text-muted-foreground max-w-2xl mx-auto">
            Join thousands of users transforming their lives with AI Fitness Coach
          </p>
        </div>

        <div className="grid md:grid-cols-3 gap-6">
          {testimonials.map((testimonial, index) => (
            <motion.div
              key={index}
              initial={{ opacity: 0, scale: 0.9 }}
              whileInView={{ opacity: 1, scale: 1 }}
              transition={{ duration: 0.5, delay: index * 0.1 }}
              viewport={{ once: true }}
            >
              <Card className="h-full">
                <CardContent className="p-6 space-y-4">
                  <div className="flex items-center gap-4">
                    <img
                      src={testimonial.avatar}
                      alt={testimonial.name}
                      className="w-12 h-12 rounded-full"
                    />
                    <div>
                      <p className="font-semibold">{testimonial.name}</p>
                      <p className="text-sm text-muted-foreground">@{testimonial.username} • Level {testimonial.level}</p>
                    </div>
                  </div>
                  <div className="flex gap-1">
                    {Array.from({ length: testimonial.rating }).map((_, i) => (
                      <Star key={i} className="w-4 h-4 fill-yellow-400 text-yellow-400" />
                    ))}
                  </div>
                  <p className="text-muted-foreground">{testimonial.content}</p>
                </CardContent>
              </Card>
            </motion.div>
          ))}
        </div>
      </section>

      {/* CTA Section */}
      <section className="container px-4 py-20">
        <Card className="bg-gradient-to-r from-purple-600 via-pink-600 to-blue-600 border-none">
          <CardContent className="p-12 text-center space-y-6">
            <h2 className="text-3xl md:text-5xl font-bold text-white">
              Ready to Transform Your Life?
            </h2>
            <p className="text-lg text-white/90 max-w-2xl mx-auto">
              Join thousands of users already achieving their fitness goals with AI-powered guidance
            </p>
            <div className="flex flex-col sm:flex-row gap-4 justify-center items-center">
              <Link href="/signup">
                <Button size="lg" variant="secondary" className="w-full sm:w-auto">
                  Start Your Journey
                  <ArrowRight className="w-4 h-4 ml-2" />
                </Button>
              </Link>
              <div className="flex items-center gap-2 text-white">
                <CheckCircle2 className="w-5 h-5" />
                <span>No credit card required</span>
              </div>
            </div>
          </CardContent>
        </Card>
      </section>

      <Footer />
    </div>
  );
}